# AUTOGENERATED! DO NOT EDIT! File to edit: ../test_app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'intf', 'classify_image']

# %% ../test_app.ipynb 1
from fastai.vision.all import * 
import gradio as gr

# %% ../test_app.ipynb 2
learn = load_learner('export.pkl')

# %% ../test_app.ipynb 3
categories = ('anger', 'contempt', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise')

def classify_image(img):
    pred, idx, probs = learn.predict(img)
    print(probs)
    return dict(zip(categories, map(float, probs)))

# %% ../test_app.ipynb 4
image = gr.Image()
label = gr.Label()

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label)
intf.launch(inline=True)
